Added _config.yml and _toc.yml files to build jupyterbook
aicoe-aiops/openshift-workload-fingerprinting pull request #49
Opened 2021-11-11 17:54 UTC by suppathak

Added _config.yml and _toc.yml files to build jupyterbook

2021-11-11 17:55 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **oindrillac** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @oindrillac` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Fopenshift-workload-fingerprinting).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/openshift-workload-fingerprinting/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["oindrillac"]} -->

2021-11-11 22:09 UTC, chauhankaranraj requested changes
Left a small comment but mostly looks good :smile:

2021-11-11 22:09 UTC, chauhankaranraj commented on _toc.yml
> +  - caption: Relevant Research Papers
```suggestion
  - caption: Previous Work Done
```
Would it make sense to keep caption names a bit broad?

2021-11-11 22:09 UTC, chauhankaranraj commented on _toc.yml
> +    - file: pyxis_mapping
```suggestion
    - file: notebooks/pyxis_mapping
```
The notebook isn't rendering for me without this prefix

2021-11-11 22:14 UTC, chauhankaranraj commented
Also, imo updating the notebook/md headers could be a pretty neat enhancement and might make the jupyterbook look even better (screenshots attached just to give an idea). Maybe this can be explored in a future PR?

![Screenshot from 2021-11-11 17-11-09](https://user-images.githubusercontent.com/15005500/141376324-bfca0e02-c0dc-4ce2-84b4-2e8610c7531f.png)

![Screenshot from 2021-11-11 17-09-35](https://user-images.githubusercontent.com/15005500/141376279-c7f54412-bc40-4f5e-9b13-61e90370f9fc.png)

2021-11-11 22:18 UTC, suppathak commented
> Also, imo updating the notebook/md headers could be a pretty neat enhancement and might make the jupyterbook look even better (screenshots attached just to give an idea). Maybe this can be explored in a future PR?

@chauhankaranraj , Thanks :),  Yes that is a good idea. I also feel the need to edit some of the headers for individual notebook.

2021-11-12 17:11 UTC, chauhankaranraj approved these changes
Thanks for the changes, looks good! Also, going forward I'd suggest creating PRs from your fork (you'll have to re-fork coz the repo visibility was changed to public) instead of a branch on upstream :)

/approve

2021-11-12 17:11 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/openshift-workload-fingerprinting/pull/49#pullrequestreview-805040598" title="Approved">chauhankaranraj</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Fopenshift-workload-fingerprinting).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aicoe-aiops/openshift-workload-fingerprinting/blob/master/OWNERS)~~ [chauhankaranraj]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-12 17:14 UTC, merged